name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
    - assets/images/grad_bear.jpg
    - assets/images/city_bookmark.jpg
    - assets/images/city_magnet.jpg
    - assets/images/city_notebook.jpg
    - assets/images/city_postcard.jpg
    - assets/images/classic_sweatshirt_neutral.jpg
    - assets/images/print_item.jpg